# Terraformの環境設定を行う共通アクション
name: "Terraform Setup Composite Action"
description: "Sets up Terraform environment, including AWS auth, init, and format check."

inputs:
  aws-iam-role:
    description: "AWS IAM role to assume"
    required: true
  aws-tf-state-bucket:
    description: "S3 bucket for Terraform state"
    required: true
  gh-dc-usermap:
    description: "JSON string for mapping GitHub actor to Discord ID"
    required: true
  tf-vars:
    description: "tfvars from Github secrets"
    required: false
    default: ""
  aws-region:
    description: "AWS region"
    required: false
    default: "ap-northeast-1"
  tf-version:
    description: "Terraform version"
    required: false
    default: "1.12.2"

outputs:
  # 後続のステップにDiscord-IDを渡す
  discord-id:
    description: "The mapped Discord user ID"
    value: ${{ steps.map_id.outputs.DC_ID }}

runs:
  using: "composite"
  steps:
    # リポジトリ名だけを取得
    - name: Get repository name without owner
      id: repo_name
      shell: bash
      run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"

    # Github Actions起動したユーザーのマッピング
    - name: Map GitHub actor to Discord ID
      id: map_id
      shell: bash
      run: |
        DC_ID=$(echo '${{ inputs.gh-dc-usermap }}' | jq -r --arg GH_ID '${{ github.actor }}' '.[$GH_ID]')
        echo "::add-mask::$DC_ID"
        echo "DC_ID=$DC_ID" >> "$GITHUB_OUTPUT"

    # AWSのOIDC認証を設定
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-iam-role }}
        aws-region: ${{ inputs.aws-region }}

    # Terraform CLIのセットアップ
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf-version }}

    # tfvarsのファイル化
    - name: Create tfvars
      if: inputs.tf-vars != ''
      shell: bash
      working-directory: terraform
      run: |
        echo "${{ inputs.tf-vars }}" > ./gh-secrets.auto.tfvars

    - name: cat-test
      if: inputs.tf-vars != ''
      shell: bash
      working-directory: terraform
      run: |
        ls -al ./
        cat ./gh-secrets.auto.tfvars

    # backend.tfのファイル化
    - name: Create backend.tf
      shell: bash
      working-directory: terraform
      run: |
        cat << "EOF" >> ./backend.tf
        terraform {
          backend "s3" {
            bucket       = "${{ inputs.aws-tf-state-bucket }}"
            key          = "${{ env.REPO_NAME }}/terraform.tfstate"
            region       = "${{ inputs.aws-region }}"
            use_lockfile = true
          }
        }
        EOF

    # Terraformの初期化
    - name: Terraform Init
      shell: bash
      working-directory: terraform
      run: terraform init

    # Terraformのフォーマットチェック
    #- name: Terraform Format
    #  shell: bash
    #  working-directory: terraform
    #  run: terraform fmt -check

    # tfvarsファイルの構文チェック
    #- name: Terraform Validate tfvars
    #  if: inputs.tf-vars != ''
    #  shell: bash
    #  working-directory: terraform
    #  run: |
    #    terraform validate -var-file=from-gh-secrets.tfvars
