name: "Terraform Manual - destroy plan"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      # AWS認証情報とTerraformバックエンド設定を環境変数として定義
      AWS_REGION: "ap-northeast-1"
      TF_VERSION: "1.12.2"

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 共通処理をComposite Actionで実行
      - name: Setup Terraform Environment
        id: setup
        uses: ./.github/actions/setup
        with:
          aws-iam-role: ${{ secrets.AWS_IAM_ROLE }}
          aws-tf-state-bucket: ${{ secrets.AWS_TF_STATE_BUCKET }}
          gh-dc-usermap: ${{ secrets.GH_DC_USERMAP }}
          aws-region: ${{ env.AWS_REGION }}
          tf-version: ${{ env.TF_VERSION }}

      # Terraformで作ったリソースの破棄の確認
      - name: Terraform Destroy Plan
        working-directory: terraform
        run: terraform plan -destroy -no-color -input=false

      # Discord通知をComposite Actionで実行
      - name: Send Discord Notification
        if: ${{ always() }}
        uses: ./.github/actions/discord-notify
        with:
          webhook-url: ${{ secrets.DC_WEBHOOK_GHAC }}
          job-status: ${{ job.status }}
          mention-id: ${{ steps.setup.outputs.discord-id }}
          title: "terraform destroy plan"
          description: "結果の詳細はWorkflowを確認してください"
